

CREATE TABLE IF NOT EXISTS Veranstaltung (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ver_name VARCHAR(250) NOT NULL,
  ort VARCHAR(250) NOT NULL,
  datum VARCHAR(250) NOT NULL,
  art VARCHAR(250) NOT NULL,
  rank VARCHAR(250) NOT NULL,
  beschreibung VARCHAR(250) DEFAULT NULL
);